export const REQUESTING_DATA = 'REQUESTING_DATA';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const UPDATE_CURRENT_PAGE = 'UPDATE_CURRENT_PAGE';